In [ ]:
import numpy as np
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 4, 3, 5, 3, 6, 1, 7, 1] }

In [ ]:
import pandas as pd
df = pd.DataFrame(exam_data)
df

        name  score  attempts
0  Anastasia   12.5         1
1       Dima    9.0         3
2  Katherine   16.5         4
3      James    NaN         3
4      Emily    9.0         5
5    Michael   20.0         3
6    Matthew   14.5         6
7      Laura    NaN         1
8      Kevin    8.0         7
9      Jonas   19.0         1

In [ ]:
selected_df=df[['name','score']]
selected_df

        name  score
0  Anastasia   12.5
1       Dima    9.0
2  Katherine   16.5
3      James    NaN
4      Emily    9.0
5    Michael   20.0
6    Matthew   14.5
7      Laura    NaN
8      Kevin    8.0
9      Jonas   19.0

In [ ]:
df[df['attempts']>3]

        name  score  attempts
2  Katherine   16.5         4
4      Emily    9.0         5
6    Matthew   14.5         6
8      Kevin    8.0         7

In [ ]:
data = {'name': ['Alice', 'Bob', 'Charlie', 'Dave'],
'age': [25, 35, 40, 28],

'gender': ['F', 'M', 'M', 'M'],

 'salary': [50000, 70000, 60000, 80000]}

df = pd.DataFrame(data)

In [ ]:
df[df['age']>30]

      name  age gender  salary
1      Bob   35      M   70000
2  Charlie   40      M   60000

In [ ]:
df[df['name'].str.contains('e')]

      name  age gender  salary
0    Alice   25      F   50000
2  Charlie   40      M   60000
3     Dave   28      M   80000

In [ ]:
df[(df['gender']=='M') & (df['salary']>65000)]

   name  age gender  salary
1   Bob   35      M   70000
3  Dave   28      M   80000

In [ ]:
df[['name','age']]

      name  age
0    Alice   25
1      Bob   35
2  Charlie   40
3     Dave   28

In [ ]:
df=pd.read_csv('bank_train.csv')
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,76,retired,married,secondary,no,2302.0,no,no,telephone,5,feb,110,1,87,2,failure,no
1,66,retired,divorced,unknown,no,53.0,no,no,cellular,12,jul,562,4,-1,0,unknown,yes
2,51,management,married,tertiary,no,2455.0,yes,no,cellular,21,jul,553,1,-1,0,unknown,yes
3,41,blue-collar,married,secondary,no,356.0,yes,no,cellular,14,may,90,5,-1,0,unknown,no
4,51,technician,married,secondary,no,-1944.0,yes,no,cellular,7,may,623,1,-1,0,unknown,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4461,33,management,married,tertiary,no,133.0,yes,no,unknown,26,may,308,4,-1,0,unknown,no
4462,39,services,divorced,secondary,no,687.0,yes,no,cellular,9,jul,869,1,-1,0,unknown,yes
4463,40,admin.,single,secondary,no,2040.0,yes,no,cellular,18,may,906,2,350,2,failure,yes
4464,31,technician,single,secondary,no,628.0,yes,no,unknown,12,may,1083,2,-1,0,unknown,no
4465,70,retired,divorced,primary,no,383.0,no,no,cellular,28,apr,50,2,-1,0,unknown,no

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4466 entries, 0 to 4465
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        4466 non-null   int64
 1   job        4466 non-null   object
 2   marital    4466 non-null   object
 3   education  4466 non-null   object
 4   default    4466 non-null   object
 5   balance    4465 non-null   float64
 6   housing    4466 non-null   object
 7   loan       4466 non-null   object
 8   contact    4466 non-null   object
 9   day        4466 non-null   int64
 10  month      4466 non-null   object
 11  duration   4466 non-null   int64
 12  campaign   4466 non-null   int64
 13  pdays      4466 non-null   int64
 14  previous   4466 non-null   int64
 15  poutcome   4465 non-null   object
 16  deposit    4466 non-null   object
dtypes: float64(1), int64(6), object(10)
memory usage: 593.3+ KB

In [ ]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,76,retired,married,secondary,no,2302.0,no,no,telephone,5,feb,110,1,87,2,failure,no
1,66,retired,divorced,unknown,no,53.0,no,no,cellular,12,jul,562,4,-1,0,unknown,yes
2,51,management,married,tertiary,no,2455.0,yes,no,cellular,21,jul,553,1,-1,0,unknown,yes
3,41,blue-collar,married,secondary,no,356.0,yes,no,cellular,14,may,90,5,-1,0,unknown,no
4,51,technician,married,secondary,no,-1944.0,yes,no,cellular,7,may,623,1,-1,0,unknown,yes

In [ ]:
df.loc[(df['education']=='primary')&(df['deposit']=='yes')]

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
29,39,blue-collar,divorced,primary,no,1317.0,yes,no,cellular,20,nov,543,1,170,4,other,yes
39,31,unemployed,single,primary,no,163.0,no,no,cellular,30,jan,707,2,2,1,other,yes
56,49,blue-collar,single,primary,no,566.0,yes,no,cellular,25,jul,979,2,-1,0,unknown,yes
66,53,blue-collar,married,primary,yes,-462.0,no,no,cellular,29,jan,470,1,-1,0,unknown,yes
103,42,blue-collar,single,primary,no,4930.0,no,no,unknown,18,jun,973,1,-1,0,unknown,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4411,55,housemaid,married,primary,no,0.0,yes,no,cellular,17,jul,1303,2,-1,0,unknown,yes
4422,80,retired,married,primary,no,1468.0,no,no,cellular,13,jan,330,3,-1,0,unknown,yes
4451,41,blue-collar,married,primary,no,143.0,yes,yes,unknown,2,jun,659,2,-1,0,unknown,yes
4452,53,blue-collar,married,primary,no,421.0,yes,no,cellular,20,nov,677,1,-1,0,unknown,yes
4458,32,blue-collar,married,primary,no,-454.0,yes,yes,cellular,18,may,801,5,355,2,failure,yes

In [ ]:
df.loc[df['deposit']=='no']

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,76,retired,married,secondary,no,2302.0,no,no,telephone,5,feb,110,1,87,2,failure,no
3,41,blue-collar,married,secondary,no,356.0,yes,no,cellular,14,may,90,5,-1,0,unknown,no
6,59,retired,married,secondary,no,136.0,no,no,cellular,6,aug,301,4,-1,0,unknown,no
7,34,blue-collar,married,primary,no,5299.0,yes,no,unknown,26,jun,75,5,-1,0,unknown,no
9,44,blue-collar,married,secondary,no,879.0,yes,no,cellular,3,apr,383,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4457,43,management,married,tertiary,no,1336.0,yes,yes,cellular,27,may,82,2,309,1,failure,no
4460,54,retired,married,secondary,no,522.0,no,yes,cellular,14,jul,81,3,-1,0,unknown,no
4461,33,management,married,tertiary,no,133.0,yes,no,unknown,26,may,308,4,-1,0,unknown,no
4464,31,technician,single,secondary,no,628.0,yes,no,unknown,12,may,1083,2,-1,0,unknown,no
4465,70,retired,divorced,primary,no,383.0,no,no,cellular,28,apr,50,2,-1,0,unknown,no

In [ ]:
df.loc[(df['loan']=='yes') & (df['deposit']=='yes')]

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
65,28,admin.,single,secondary,no,0.0,yes,yes,cellular,18,may,390,5,-1,0,unknown,yes
77,32,technician,single,secondary,no,324.0,no,yes,cellular,23,feb,432,1,-1,0,unknown,yes
83,48,services,divorced,secondary,no,-276.0,yes,yes,cellular,13,may,674,1,-1,0,unknown,yes
86,45,admin.,divorced,secondary,no,397.0,yes,yes,cellular,22,may,582,1,95,2,success,yes
105,33,unemployed,single,secondary,no,2066.0,no,yes,cellular,9,sep,305,1,749,2,failure,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4406,37,management,married,secondary,no,5447.0,yes,yes,cellular,17,nov,1789,1,-1,0,unknown,yes
4449,26,blue-collar,single,secondary,yes,81.0,no,yes,cellular,8,jul,803,2,-1,0,unknown,yes
4451,41,blue-collar,married,primary,no,143.0,yes,yes,unknown,2,jun,659,2,-1,0,unknown,yes
4454,30,blue-collar,single,secondary,no,155.0,yes,yes,cellular,9,jul,1426,3,-1,0,unknown,yes
4458,32,blue-collar,married,primary,no,-454.0,yes,yes,cellular,18,may,801,5,355,2,failure,yes

In [ ]:
df.loc[(df['education']=='secondary') & (df['deposit']=='no')]

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,76,retired,married,secondary,no,2302.0,no,no,telephone,5,feb,110,1,87,2,failure,no
3,41,blue-collar,married,secondary,no,356.0,yes,no,cellular,14,may,90,5,-1,0,unknown,no
6,59,retired,married,secondary,no,136.0,no,no,cellular,6,aug,301,4,-1,0,unknown,no
9,44,blue-collar,married,secondary,no,879.0,yes,no,cellular,3,apr,383,1,-1,0,unknown,no
10,34,services,married,secondary,no,1637.0,yes,no,cellular,21,nov,107,4,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4446,35,services,married,secondary,no,0.0,yes,no,cellular,24,jul,810,1,-1,0,unknown,no
4453,31,services,married,secondary,no,505.0,no,no,cellular,11,jul,773,3,-1,0,unknown,no
4456,54,blue-collar,married,secondary,no,-102.0,yes,no,cellular,27,aug,164,7,-1,0,unknown,no
4460,54,retired,married,secondary,no,522.0,no,yes,cellular,14,jul,81,3,-1,0,unknown,no
4464,31,technician,single,secondary,no,628.0,yes,no,unknown,12,may,1083,2,-1,0,unknown,no

In [ ]:
df.loc[(df['poutcome']=='success') & (df['deposit']=='yes')]

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
19,76,self-employed,married,unknown,no,4984.0,no,no,telephone,28,apr,403,1,182,1,success,yes
21,33,admin.,married,tertiary,no,79.0,yes,no,cellular,5,may,389,1,195,4,success,yes
45,71,retired,divorced,secondary,no,0.0,no,no,cellular,26,feb,771,1,171,1,success,yes
51,68,retired,married,secondary,no,1146.0,no,no,cellular,13,may,356,1,71,5,success,yes
52,46,management,married,tertiary,no,273.0,yes,no,cellular,18,mar,910,2,184,4,success,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4338,38,admin.,divorced,secondary,no,19.0,yes,no,cellular,5,feb,1130,3,251,2,success,yes
4372,20,student,single,secondary,no,215.0,no,no,cellular,24,feb,175,1,92,6,success,yes
4376,42,technician,married,secondary,no,994.0,yes,no,cellular,12,nov,227,3,93,6,success,yes
4408,29,housemaid,single,tertiary,no,19.0,no,no,cellular,4,may,268,1,88,4,success,yes
4448,27,blue-collar,single,secondary,no,535.0,no,no,cellular,16,aug,265,3,95,4,success,yes

In [ ]:
df.loc[df['age']>30,['name','salary']]

KeyError: "None of [Index(['name', 'salary'], dtype='object')] are in the [columns]"